/**
 * Disclaimer text for onboarding and settings screens.
 * Single source of truth for legal/safety disclaimers.
 */

export const DISCLAIMER_TEXT = {
  intro: 'Confidant is designed to be a private space for reflection and emotional expression. However, it is important to understand:',

  bullets: [
    'This app is NOT a substitute for professional mental health care, therapy, or medical advice.',
    'Conversations are generated by an on-device AI and should not be considered professional guidance.',
    'If you are experiencing a crisis or suicidal thoughts, please contact 988 immediately.',
    'For ongoing mental health concerns, please consult a licensed mental health professional.',
  ],

  acknowledgmentLabel: 'I understand and acknowledge this disclaimer',
} as const;
